feat: 多色进度时钟
RollRollGo/notion_html_widgets pull request #14
Opened 2024-04-30 13:32 UTC by XuQuan-nikkkki

2024-05-01 03:56 UTC, XuQuan-nikkkki commented
测试链接： https://xuquan.site/notion_html_widgets/progress-clock/

2024-05-01 14:00 UTC, PapayaHUANG requested changes

2024-05-01 14:00 UTC, PapayaHUANG commented on progress-clock/script.js
> +// 因此将降低 alpha 后的颜色再转为 alpha 为 1 的值，再赋值给 fadedColor
这里还是一个不懂就问哈：为什么不直接用 rgba 来表示颜色，可能会更容易表达出来两种颜色之间的逻辑关系？

2024-05-01 14:00 UTC, PapayaHUANG commented on progress-clock/script.js
> +}
```suggestion
function updateElementContentById(id, content) {
  document.getElementById(id).textContent = content;
}
```

2024-05-01 14:00 UTC, PapayaHUANG commented on progress-clock/script.js
> +}
这三个逻辑是通用
如果只 `getTimeInfo()` 一次，然后再调用`updateElementContentById`三次，这样写是不是会简单一些啊？

2024-05-01 14:00 UTC, PapayaHUANG commented on progress-clock/style.css
> +
咱把多余的空格删一删？

2024-05-01 14:00 UTC, PapayaHUANG commented on progress-clock/style.css
> +
这里也有多余的空格

2024-05-02 03:14 UTC, XuQuan-nikkkki commented on progress-clock/style.css
> +
这个空行是特地留的。。。只是我留的不是特别规范，我记得有 css lint 会把不同类型的样式隔开的，比如布局是一块，字体是一块

2024-05-02 03:15 UTC, XuQuan-nikkkki commented on progress-clock/script.js
> +}
这样的话单个函数就不是 single responsibility 了，我不太倾向于这样写

2024-05-02 03:23 UTC, XuQuan-nikkkki commented on progress-clock/script.js
> +// 因此将降低 alpha 后的颜色再转为 alpha 为 1 的值，再赋值给 fadedColor
这里写注释就是想解释 fadedColor 不是单纯把 a 调低了，是我希望它看起来是 a 调低了的颜色，但是如果采用调低 a 的方式会由于透明度降低导致下一层的颜色透过来，所以我是对 a 调低之后的颜色重新取值了。举个例子，这个浅色就是深色的 a 降低之后的值，但我用的 hex 对应的 rgba 应该是截图里的值，所以用 rgba 表示也看不出两者之间的关系
![image](https://github.com/RollRollGo/notion_html_widgets/assets/28928053/177a232b-ae71-4bd7-806d-40ad15e0aa9c)

直接写了 hex 是因为我是从一个配色方案里取的值，它写的 hex，我就直接用了，没有再转一遍

2024-05-02 03:25 UTC, XuQuan-nikkkki commented on progress-clock/script.js
> +}
赶紧回去查了一下，已经忘记还有 textContent 和 innerText 这几个概念了

2024-05-02 04:20 UTC, XuQuan-nikkkki commented on progress-clock/script.js
> +// 因此将降低 alpha 后的颜色再转为 alpha 为 1 的值，再赋值给 fadedColor
我在注释里补了一下例子，你看看还有没有疑问

2024-05-02 04:20 UTC, XuQuan-nikkkki commented on progress-clock/script.js
> +}
改成用 textContent 了

2024-05-02 04:21 UTC, XuQuan-nikkkki commented on progress-clock/style.css
> +
空行我先删了，这部分样式比较少，我感觉样式多的时候空行还挺好的，就比较视觉上区分不同关注点

2024-05-02 04:22 UTC, XuQuan-nikkkki reviewed
fixed in 14743d34431a6a522

2024-05-02 13:01 UTC, PapayaHUANG commented on progress-clock/style.css
> +
哦，就跟 js 函数里面有空格一样～

2024-05-02 13:04 UTC, PapayaHUANG approved these changes

2024-05-02 13:07 UTC, merged